### ISSUE TITLE
Project-wide genome mask

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#13]
Do we use
- Oxford mask
- Maha (Max Marin) mask

I prefer Max's mask for various reasons (mostly the transparency of how it was created). But, not sure if you are hesitant to move away from the Oxford one @iqbal-lab?  

If we do want to use Max's one I guess we probably need to run it by them first?

**Comment by iqbal-lab** [comment]
Two aspects

### what metrics are we primarily analysing our results with

1. concordance with COMPASS 
This means,
a) how many positions do both COMPASS and pandora say there is a non-ref
b) at positions where both make a call (non-ref), what % of them do we agree with COMPASS
For this, there is zero value in having any calls outside the compass region because there are no calls to compare with.  ie might as well have COMPASS mask.

2. concordance of clustering
This is a bit more complicated

3. comparison to truth assembly - we are bound to try with/out masks here

### how do we explain in our paper

compass is published. Max's is not, but is explicable (although one half of it i have mild issues with). Maha has asked us not to publicise it yet til they publish, and that paper is taking a long time


### conclusion

i vote compass.
I agree it would be good to have a better, reproducibly generated mask, but i don't think i would do it max's way. So i'd rather stick to compass for now, and if we get to a stage where we have some results and they look ok, and have breathing space, could look at improving the mask.

(IMO the way to go is combining kmer-multiplicity or mappability (as max does) with consistency of coverage across samples )
