### ISSUE TITLE
Use FORGe to rank variants

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#2]
[FORGe][forge-paper] is a tool for ranking variants and building an optimal graph genome. We are specifically interested in using it to help us select the variants we want to use for constructing our various PRGs.

[forge-paper]: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1595-x

**Comment by mbhall88** [comment]
To rank variants, FORGe requires a reference fasta file and a `1ksnp` variant file. They provide a [script][script] for converting a VCF to this `1ksnp` format.  

I suspect (from looking at the code) that this will not work out of the box on our cryptic VCFs. As a first pass, I will try and run it on the comas VCF and figure out what is required to get the script to convert the VCF (i.e. what errors to I get).

[script]: https://github.com/langmead-lab/FORGe#vcf_to_1ksnppy

**Comment by mbhall88** [comment]
After running the script on the comas VCF with H37Rv as the reference genome I get

```
$ python3 $script --vcf cryptic_release.2020-04.comas.vcf --reference $REF --out comas.1ksnp
Found 0 SNPs
0-indexed: 0 / 0
1-indexed: 0 / 0
```

It [looks like](https://github.com/langmead-lab/FORGe/blob/7fe3d29094b909d0c55ba480dddad58457d27cab/src/vcf_to_1ksnp.py#L42-L50) the conversion script infers whether the entry is a SNP based purely on the `VT` INFO field. As the cryptic VCFs don't have this field I will either need to add it, or filter the VCF to only SNPs (and INDELs?) using `bcftools view --types snps <in.vcf>` as it infers the variant type based on comparing the REF and ALT contents.  
I tried digging into htslib to see exactly how they infer this type but the C files are enormous and it's almost impossible to trace variables across functions etc. Is it as simple as saying if REF length is 1 and ALT length is 1 then it is a SNP?

**Comment by iqbal-lab** [comment]
Just composing a reply, but will take most of today to do it.

**Comment by iqbal-lab** [comment]
Last time we spoke i was really not properly on top of how FORGE worked - i wasn't really expecting you to suggest using FORGE as a way to build our primary PRGs so much as a comparison. i've re-read it and thought a bit. 


## How does FORGE prioritise variants to go into a PRG?



There are a couple of main approaches trialled in FORGE, and each admits a modification to avoid blowups, as follows. All of this is predicated on building a graph from an unphased VCF (with a minor caveat below)



## Maximising population coverage

PopCovg is the probability that a random k-mer from the population lies in the PRG (or perhaps a random kmer overlapping a variant, but i think it does not matter).

Once you undress it, maximising PopCovg is essentially saying we want to prioritise variants by frequency.

There is a technical hitch - because FORGE default assumes VCF inputs are unphased, any k-mer overlapping an allele is affected by the genotype of adjacent variants within k bases. This is a pain - they want to be able to build a total ordering of variants/alleles, and this is difficult if the score of a SNP depends on its context. The workaround is to invert the problem, and imagine the complete graph of all population variants, and ask how much PopCovg drops when removing this variant. This is clever - but note that by using unphased input, you immediately create a blowup problem in areas of dense variation, and removing a variant from a dense graph still leaves a graph dense with variation that has never been seen.

Does it work? Yes it does - but note that in the discussion they indeed confirm that you get the same results with a population frequency filter. Which makes sense.

## Comment

PopCovg is basically the best you can do if you really want to filter by allele frequency, but you have unphased VCFs, so need to make the complete graph (which is stuffed full of haplotypes and recombinants that have never been seen), and then remove stuff from it.

An alternative is to work from haplotypes, sample haplotypes by frequency, and include all the kmers from all the dense variants that are in that haplotype. You preserve linkage, avoid blowup without discarding linked alleles, and maximise mapping to that haplotype. Sampling haplotypes by frequency (which == uniform sampling provided you have a well-sampled population) will do this.

_And that, of course, is what make-prg is designed for_ - it is precisely designed to avoid blowup problems by preserving linkage in regions of dense variation. In our TB case, if we pick genomes at random (eg pick 100 VCFs/genomes randomly) and then turn that VCF into an implied genome, and collect all these implied genomes and run make-prg, you are maximising popcovg, with implicit blowup avoidance.

## Hybrid

Here we just rescale the frequency of a given allele by 1 over the multiplicity of the overlapping k-mer. This discourages us from adding alleles that are repeats.

In order to get a k-mer from a variant and compare across the genome, this takes advantage of phasing info.

How does it work? No better really - you achieve the same maximum number of mapped reads (this is figure 1). You can add more and more SNPs to the PRG this way without so much drop in %-reads aligned - this is because HISAT refuses to map any multimapping read, so creating repeats leads to unmapped reads.

I don't really like this because it tries to hide uncertainty in mapping, but i do get the value.


## Blowup Avoidance

Basically the user is allowed to decide what % of nearby SNPs are allowed to be added to the PRG in addition to a focal SNP. Default in the paper is 0.5. Obviously this drops the % of reads mapped , but not by much.



# How does FORGE fit in with head-to-head plans?



I think it's fine, esp in thesis rather than the head-to-head paper, to compare how FORGE does compared with the pandora approach. But i think it is important to preserve the benefit of the make-prg approach. ie i see the default approach as

1. collect a random subsample of VCFs and create implied genomes (or genes/loci, rather). Note that random sampling is precisely designed to pick up the higher frequency haplotypes first.
2. pass into make-prg

This is as or more principled than the popcovg approach - both are seeking to achieve the same thing (maximise the frequency of the included alleles), but this approach avoids blowup by maintaining linkage between densely clustered variants.

So the sparse and dense PRGs would be built by selecting 750 or 1500 of the 15000 VCFs rather than variants with frequency <=5% or 10%.

**Comment by mbhall88** [comment]
So, to be clear, what you are saying is to randomly subsample from the VCF sample columns and then include any variant that exists in each of those samples?  

Do you want to do this subsampling from the whole VCF or on the lineage-specific VCFs, or we could split the VCFs into lineage 1-4 and 5-7 and sample from those?

**Comment by iqbal-lab** [comment]
Yes to paragraph 1.
Yes to paragraph 2. that's what we thought we were saying in the github issue about Lineage specific vcfs (however this is contradicting what I said back around the time of your TAC, sorry, as I just said take variants of given frequency).

**Comment by mbhall88** [comment]
> Yes to paragraph 2. that's what we thought we were saying in the github issue about Lineage specific vcfs (however this is contradicting what I said back around the time of your TAC, sorry, as I just said take variants of given frequency).

Paragraph 2 wasn't a yes/no question so I'm confused which of the three options you want to go with?
1. Subsample whole VCF
2. Subsample lineage-specific VCFs
3. Subsample from 2 VCFs: Lineage 1-4 and 5-7

**Comment by iqbal-lab** [comment]
Doh,sorry. I suggest a slight mod of option 2
 -  subsample from lineage specific VCFs for lineages with >100 samples
 - take entire lineage specific VCF if it contains <=100 samples
I think you will find lineages 1-4 have >1000 samples and the others will have relatively few.
