### ISSUE TITLE
Split H37Rv based on annotation

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/head_to_head_pipeline#9]
We will base our local PRGs on genes and intergenic regions from the [H37Rv annotation][annotation]. 

[annotation]: https://github.com/mbhall88/head_to_head_pipeline/blob/master/data/H37Rv_PRG/resources/h37rv.gff3

**Comment by mbhall88** [comment]
Regarding how to cut out intergenic regions (as they are not in the annotation): For H37Rv it is reasonably straight-forward - take the inverse intervals in the GFF and cut these out of H37Rv.
To that end, I have done some analysis on the lengths of IGRs.
Below is a plot of all the IGR lengths
```
100.00% (0) of IGRs are >= 1
84.74% (872) of IGRs are >= 5
80.53% (1113) of IGRs are >= 10
69.07% (1768) of IGRs are >= 30
61.34% (2210) of IGRs are >= 50
48.39% (2950) of IGRs are >= 100
28.25% (4101) of IGRs are >= 300
10.27% (5129) of IGRs are >= 1000
```
![image](https://user-images.githubusercontent.com/20403931/82976483-8cd01200-a022-11ea-8c13-cbe9b5e1592a.png)


So we just need to decide on a minimum length cutoff (and maybe a maximum?)

**Comment by mbhall88** [comment]
@iqbal-lab I forgot what length we decided on for the minimum?

**Comment by iqbal-lab** [comment]
So, here's an idea. We know from these plots
https://github.com/iqbal-lab/pandora1_paper/issues/133#issuecomment-608156555
that even with illumina data, for short genes, we are likely to miss them (fail to detect the gene and therefore downstream we get no SNPs). By the time we get to 500bp long, we essentially miss zero. So why not aggregate adjacent genes and IGRs until we are >=500bp. As for max, i agree with what you said on slack - suggest trying no max. That plot makes it look like there are a handful bigger than 5kb. The main issue is if the VCF contains tonnes of SNPs within a 6kb gene and then make-prg becomes expensive - you'd end up with one slow gene in your loop. So
how about

1. min=500, no max (simplest solution, see what happens)
2. min=500, have a max number of alt alleles allowed in your region. so if there is a tonne of variation, you end up with a smaller region. (check out --variants_per_split option of minos. minos does chunking of the genome for the regenotyping pipeline, and allows you to either say you want N chunks, or to set a max number of alleles per chunk). I don't think this chunking is easily accessible in minos as a thing you can call on its own, otherwise this would offer you an easy option

**Comment by iqbal-lab** [comment]
Ah sorry of course the minos thing would ignore the annotation.
Anyway FYI, from martin, 
There’s this:
```
$ minos make_split_gramtools_build --help
usage: minos make_split_gramtools_build [options] <outdir> <VCF file> <ref FASTA>
Split VCF/ref into pieces and run gramtools build. The resulting directory can
be used with "minos adjudicate --gramtools_build_dir", so that the same build
can be used on multiple samples without generating it during each run of minos
positional arguments:
  outdir                Name of output directory
  vcf_file              Input VCF file to be split
  ref_fasta             Reference FASTA file
optional arguments:
  -h, --help            show this help message and exit
  --total_splits INT    Split VCF, aiming for this many chunks with the same
                        number of variants in each chunk (see also
                        --variants_per_split and --alleles_per_split) [100]
  --variants_per_split INT
                        Split VCF, aiming for this many variants in each
                        split. If used, --total_splits is ignored
  --alleles_per_split INT
                        Split VCF, aiming for this many alleles in each split.
                        If used, --total_splits is ignored
  --max_read_length MAX_READ_LENGTH
                        This number is used with gramtools build --max-read-
                        length [200]
  --gramtools_kmer_size INT
                        This number is used with gramtools build --kmer-size
                        [10]
  --threads INT         Number of gramtools builds to run in parallel [1]

```

ie use the --alleles_per_split option. However it would run gramtools index, so you would maybe want to kill it when that starts running

**Comment by iqbal-lab** [comment]
Again, just to make sure i'm not confusing, i'm suggesting option 1 here, and making you aware of two if you find you have some chunks with vast numbers of sites.

1. min=500, no max (simplest solution, see what happens)
2. min=500, have a max number of alt alleles allowed in your region. so if there is a tonne of variation, you end up with a smaller region.

**Comment by mbhall88** [comment]
After splitting H37Rv and merging short intervals based on rule 1 above, we have 2_655 loci. The longest of those is 24_040bp, which is a concatenation of multiple genes and an intergenic region `fadD26+ppsA+ppsB+ppsC+ppsD+IGR:3267731-3267737`. 

These skeleton loci are located on noah at `/hps/nobackup/research/zi/projects/tech_wars/data/H37Rv_PRG/prgs/reference_loci/NC_000962.3`. There is also a csv file containing information about all loci: `/hps/nobackup/research/zi/projects/tech_wars/data/H37Rv_PRG/prgs/reference_loci/loci-info.csv`

**Comment by mbhall88** [comment]
## Statistics and plots on loci lengths

![image](https://user-images.githubusercontent.com/20403931/85086148-2bfcb980-b21d-11ea-9aa6-a49d32609829.png)


|       |        0 |
|:------|---------:|
| count |  2582    |
| mean  |  1708.57 |
| std   |  1258.99 |
| min   |   502    |
| 25%   |   954    |
| 50%   |  1385    |
| 75%   |  2011.75 |
| max   | 24040    |
